# Generated by Django 5.2.11 on 2026-02-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0001_initial"),
        ("threads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="tags",
            field=models.ManyToManyField(
                blank=True, through="engagement.ThreadTag", to="engagement.tag"
            ),
        ),
    ]
