# Generated by Django 5.2.11 on 2026-02-21 22:00
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=180, null=True, unique=True)),
                ("bio", models.TextField(blank=True)),
                ("avatar", models.ImageField(blank=True, null=True, upload_to="people/avatars/")),
                ("is_verified", models.BooleanField(default=False)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
    ]
